---
- name: create an ec2 instance for application
  include: ec2instance.yml

- name: Add the newly created EC2 instance(s) to host group appserver
  lineinfile: dest={{ hostpath }}
              regexp={{ item.public_ip }}
              insertafter='\[app_server\]'
              line="{{ item.public_ip }} {{hoststring}}"
              state=present
  with_items: "{{ ec2.instances }}"


- wait_for: path={{ hostpath }} search_regex={{hoststring}}

- name: Wait for SSH to come up
  local_action: wait_for
                host={{ item.public_ip }}
                port=22
                state=started
  with_items: "{{ ec2.instances }}"
